1. try-catch可以捕获什么异常？

- [ ] revert()
- [ ] require()
- [ ] assert()
- [x] 以上都可以

2. 以下异常返回值类型为bytes的是：

- [ ] revert()
- [ ] require()
- [ ] assert()
- [x] 以上都是

3. try-catch捕获到异常后是否会使try-catch所在的方法调用失败？

- [ ] 会
- [x] 不会

4. try代码块内的revert是否会被catch本身捕获？

- [ ] 会
- [x] 不会